learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
    
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.conf.urls import url
from django.urls import path

from learning_logs.models import Topic

from . import views

app_name = "learning_logs"
urlpatterns = [
    # Home Page
    path('', views.index, name="index"),
    # page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name="topic"),
    # Page for adding a new topic.
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry. 
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL pattern for users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
    # path('profile/<int:user_id>/', views.user_profile, name='profile'),
    # path('create/', views.create_profile, name="create_profile"),
]

learning_logs/models.py
from typing import Text
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=True)


    def __str__(self):
        """return a string representation of the model."""
        return self.text.title()

## add update time.
class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self) -> str:
        """Return a string representation of Entries."""
        if len(self.text) < 50:
            return f"{self.text}"
        return f"{self.text[:50]}..." 
    

learning_logs/forms.py
from django import forms

from .models import Entry, Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'public']
        labels = {'text': ''}
        


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django import forms
from django import http
from django.forms.widgets import RadioSelect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic,Entry
from .forms import TopicForm, EntryForm



# Create your views here.

def index(request):
    """The home page for learning_logs."""
    home_page_topics = Topic.objects.filter(public=True).order_by('-date_added')
    context = {"topics": home_page_topics}
    return render(request, 'learning_logs/index.html', context)



def topics(request):
    """Shows all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)



def topic(request, topic_id):
    """Show a single topic and its all entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user. 
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by("-date_added")
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data sbmitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit current entries."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with current entry. 
        form = EntryForm(instance=entry)
    else:
        # POST data submitted, process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context =  {'entry': entry, 'topic': topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1,
 shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <link id="myStyleSheet" rel="stylesheet" type="text/css" href="{% static 'learning_logs/dark.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
<body>
        <nav class="navbar navbar-expand-md mb-4 ">
        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
         Learning Log</a>
         
         <button class="btn btn-dark mx-auto" onclick="swapStyle(dark)"><i class="fas fa-moon"></i></button>
         <button class="btn btn-light mx-auto" onclick="swapStyle(light)"> <i class="fas fa-sun"></i> </button>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
         data-target="#navbarCollapse" aria-controls="navbarCollapse"
         aria-expanded="false" aria-label="Toggle navigation" >
         <span><i class="fas fa-caret-up"></i></span></button>
         

        
        
        <div class="collapse navbar-collapse" id="navbarCollapse">

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'learning_logs:topics' %}" class="nav-link">Topics
                    </a>
                </li>
            

            

            

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{user.username}}</span>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:logout' %}" class="nav-link">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'users:register' %}" class="nav-link">Register</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="nav-link">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    

    <script type="text/javascript">
        var dark = "{% static 'learning_logs/dark.css' %}"
        var light = "{% static 'learning_logs/light.css' %}"
        var setTheme = localStorage.getItem("theme")
        console.log("theme:", setTheme)
        if (setTheme == null){
            swapStyle(light)
        }else{
            swapStyle(setTheme)
        }

        function swapStyle(sheet){
            document.getElementById('myStyleSheet').href = sheet
            localStorage.setItem('theme', sheet)
        }

        function check_navbar(){
            var is_clicked = $("#navbarCollapse").hasClass("collapsed");
            alert(is_clicked);
        }

    </script>



</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

    <p>Edit Entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save Changes</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3 text-center">Online Journal</h1>
    </div>

{% endblock page_header %}


{% block content %}
    
    
    <div class=text-center>
    <a href="{% url 'learning_logs:new_topic' %}"> <i class="fas fa-plus" aria-setsize="7x"> </i>   </a> 
    </div>  

    {% for topic in topics %}

            <div class="card mb-5 mt-5">
                <div class="card-body bg-dark">
                    <h6 class="text-right">@{{topic.owner}} {{ topic.date_added}} Public</h6>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
                </div>
            </div>
    
    {% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Add Entry</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name='submit'>Add topic</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load humanize %}

{% block page_header %}
    <h3>{{topic}}</h3>
{% endblock page_header %}

{% block content %}


    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add Entry  </a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M, d Y H:i' }}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit Entry</a>
                </small>
            </h4>
            <div class="card-body">
                {{entry.text|linebreaks}}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header%}

{% block content %}

    <ul>
        {% for topic in topics %}
        <li><h4>
            
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
        </h4></li>
        {% empty %} 
        <li><h3>No topics has been added yet.</h3></li>
        {% endfor %}
    </ul>

    <h5><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h5>

{% endblock content %}